//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "bit_test")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        // column_type = "custom(\"BIT(32)\")"
        // column_type = "Bit(Some(32))"
    )]
    // pub field: String,
    pub field: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
